"""Ajout des colonnes de phase aux bouteilles

Revision ID: 002
Revises: 001
Create Date: 2026-03-13 20:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "002"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bottles", sa.Column("jeunesse_end", sa.Integer(), nullable=True))
    op.add_column("bottles", sa.Column("maturite_end", sa.Integer(), nullable=True))
    op.add_column("bottles", sa.Column("apogee_end", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bottles", "apogee_end")
    op.drop_column("bottles", "maturite_end")
    op.drop_column("bottles", "jeunesse_end")
    # ### end Alembic commands ###
